version: '3.8'

services:
  # FastAPI backend service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/notaidoc
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_VISION_CREDENTIALS=${GOOGLE_VISION_CREDENTIALS}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - notaidoc-network

  # PostgreSQL database for local development
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notaidoc
    restart: unless-stopped
    networks:
      - notaidoc-network

  # Development database UI
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@notaidoc.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - notaidoc-network

volumes:
  postgres_data:

networks:
  notaidoc-network:
    driver: bridge 